pipeline {
  agent none

  environment {
    MAJOR_VERSION = 1
  }

  stages {
    stage('Unit Tests') {
      agent {
        label 'apache'
      }
      steps {
        dir('cicd/sample') {  // Move into the subpath
            sh 'ant -f test.xml -v'
            junit 'reports/result.xml'
        }
      }
    }
    stage('build') {
      agent {
        label 'apache'
      }
      steps {
        dir('cicd/sample') {  // Move into the subpath
            sh 'ant -f build.xml -v'
        }
      }
      post {
        success {
          dir('cicd/sample') {  // Move into the subpath
            archiveArtifacts artifacts: 'dist/*.jar', fingerprint: true
          }        
        }
      }
    }
  }
  post {
    failure {
      emailext(
        subject: "${env.JOB_NAME} [${env.BUILD_NUMBER}] Failed!",
        body: """<p>'${env.JOB_NAME} [${env.BUILD_NUMBER}]' Failed!":</p>
        <p>Check console output at &QUOT;<a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>&QUOT;</p>""",
        to: "brandon@linuxacademy.com"
      )
    }
  }
}
