# 1.22.9-1741020486
FROM registry.access.redhat.com/ubi9/go-toolset@sha256:6402ad7886fb3bdaa950c89bdf338f8dbedde54c16bddb1157ebb8691b2def50 as builder
ARG TARGETARCH
USER root
WORKDIR /workspace
COPY . .

RUN GOARCH=${TARGETARCH} make build 

# ubi 9.5-1732804088
FROM registry.access.redhat.com/ubi9/ubi:9.5-1739751568
ARG TARGETARCH
LABEL org.opencontainers.image.authors="Adrian Riobo"

COPY --from=builder /workspace/out/seminario /usr/local/bin/

ENTRYPOINT ["seminario"]
